name: CI
on: [push, pull_request]
jobs:
  cpp-lint:
    name: C++ Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install clang-format
      run: sudo apt-get install clang-format

    - name: clang-format
      run: clang-format --dry-run --verbose source/* source/drivers/*